name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: GitHub Security Code Scan
      uses: github/codeql-action/init@v2
      with:
        languages: javascript # Or the appropriate language for your project
        queries: security-extended,#secrets

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Build Docker Image
      run: docker build -t my-docker-image . # Replace my-docker-image with your desired image name

    - name: Run Trivy
      uses: aquasecurity/trivy-action@master # Use the latest version or a specific tag
      with:
        image-ref: my-docker-image:latest # Replace my-docker-image with your image name
        format: 'table'
        exit-code: '0' # Set to a non-zero value to fail the CI on vulnerabilities
        ignore-unfixed: true
        vuln-type: 'os,library'
