name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install test dependencies
      run: npm install --save-dev supertest

    - name: Run tests
      run: npm test

    - name: GitHub Security Code Scan
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Display CodeQL Report
      run: |
        if [ -f results/javascript.sarif ]; then
          cat results/javascript.sarif
        else
          echo "CodeQL SARIF report not found."
        fi

    - name: Build Docker Image
      run: docker build -t my-docker-image:latest .

    - name: Run Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
        image-ref: my-docker-image:latest
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
